homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -37.7168
  longitude: 145
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 89
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Melbourne
# Enables the frontend
frontend:
# Enables configuration UI
config:
# Web server details
http:
  api_password: !secret http_password
  base_url: www.eardal.com:8123
# Checks for available updates
updater:
# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:
# Enables support for tracking state changes over time.
history:
# View all events in a logbook
logbook:
# Track the sun
sun:
# Text to speech
tts:
  platform: google
# Add wemo devices with static IP
#wemo:
#  static:
    # - 192.168.1.203
    # - 192.168.1.193
#    - 192.168.1.128
    # - 192.168.1.217
    # - 192.168.1.26
# Variables
input_boolean:
  away_mode:
    name: Away Mode
    initial: off
    icon: mdi:security-home
  at_home_tonight:
    name: Neil and Callum at home
    initial: off
    icon: mdi:account-multiple
  lounge_motion_mode:
    name: Lounge lighting on with motion
    initial: on
    icon: mdi:transit-transfer
  lounge_low_light_motion_mode:
    name: Lounge lighting on with motion when there is low light
    initial: on
    icon: mdi:transit-transfer
  lounge_off_timer_mode:
    name: Lounge lighting off with timer
    initial: on
    icon: mdi:timer
  heater_off_timer_mode:
    name: Heater off with timer
    initial: on
    icon: mdi:timer
  flic_1:
    name: Flic 1 click
    initial: off
    icon: mdi:timer
  flic_2:
    name: Flic 2 clicks
    initial: off
    icon: mdi:timer
  flic_3:
    name: Flic hold
    initial: off
    icon: mdi:timer  
  system_initialised:
    name: System Initialised
    initial: off
    icon: mdi:timer  
    # All split files
input_select:
  lounge_scene:
    name: Scene
    options:
     - 'Day'
     - 'Night'
     - 'Movie'
     - 'Lights Off'
     - 'Lights On'
    initial: 'Night'
    icon: mdi:panda
automation: !include automation.yaml
zone: !include zones.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
notify: !include notify.yaml
media_player: !include media_player.yaml
script: !include scripts.yaml
#scene: !include scenes.yaml