- platform: asuswrt
  host: 192.168.1.1
  username: !secret asuswrt_username
  password: !secret asuswrt_password
  interval_seconds: 10
  consider_home: 180
  track_new_devices: yes
- platform: bluetooth_tracker
