- platform: broadlink
  host: 192.168.1.27
  mac: "b4:43:0d:fc:1c:a9"
  switches:
    tv_lg:
      friendly_name: "LG Tv Power"
      command_on: 'JgBYAAABIJISExETETcSEhISEhQQFBETETcROBESEjcRNhM1EjcTNRMTERISNxEUERMSExE2EjYSNhM2EhIROBE3ETcREhITEgAFGwABH0oSAAwzAAEfShEADQU='
      command_off: 'JgBYAAABHpISEhMSETYTEhATEhQREhMSEDgRNxISEjcRNxE1EjcSNhM1EhISNhEUERETEhI1EjcSEhE4ExARNxI3ETYTERMSEQAFGAABIEgTAAwpAAEfSRIADQU'
    tv_lg_hdmi1_hdmi2:
      friendly_name: "LG Tv HDMI12"
      command_on: 'JgBIAAABIZMRExITEjYSExMRERURExEUEDkRNxEUEjYSNhM3ETcSNxITETgSNhI2ExMQExE4ETYSNxIUERMSExE4ETcRFBETEQANBQ=='
      command_off: 'JgBQAAABJJMSEhISETgSEhITEBMSEhMSETcSNxMREjcSNxI3EjcSOBETERITNhM2EhITERM2EzcRNxI3ExISEhI3EjcRExETEgAFLQABJEoRAA0FAAAAAAAAAAA='
    tv_lg_hdmi3:
      friendly_name: "LG Tv HDMI3"
      command_on: 'JgBIAAABIZMSFBISETgRExEUERQQFBETEjcTNhMSETgRNxE3EjcROBM2ERMSFBE4ERMSNxM2EjUSFBE2ETgRExM2ExITEhATEwANBQ=='
    tv_lg_av1_av2:
      friendly_name: "LG Tv AV12"
      command_on: 'JgBIAAABIpQPFBITETgSEw8UEhQSEhEVDzgSOBAUETgQOQ84EjgRNxITETgSExA5EDgREhI3EhMROBMSEDkQFBETEjYTEhE4EQANBQ=='
      command_off: 'JgBIAAABH5YPFBETETgUERAUEBURFBATETgROBEUETcSNxE4ETcSOBISEBUQFREUEjUSFBA5ETcRNxE4ETkQOBAUEjcRFRAUEQANBQ=='
    fujitsu_ac_fan:
      friendly_name: "AC Fan Lounge"
      command_on: '260066006e340d0e0d0d0e280d0e0e270d0e0e0d0f0b0d290d280d0e0d0e0e0c0d290e270d0e0d0e0d0d0d0e0d0e0e0c0f0c0d0e0d0e0e0c0e0d0d0e0d0e0e270d0e0e0c0e0d0c0f0d0e0e0c0d0e0d280e0d0d0e0d0e0e0c0d290e0d0d0d0d0e0e0d0e0c0d0e0d000d05'
      command_off: '260066006b350e0d0e0d0d280e0c0f270d0e0e0d0d0d0d290e270d0e0e0d0e0c0d290d280d0e0e0d0e0c0d0e0d0e0e0d0d0d0d0e0d0e0d0d0d0e0d0e0e0d0d280e0d0e0c0d0e0d0e0e0d0d0d0d0e0e270e0d0d0e0e0d0e0c0e280d0c0f0d0d0e0f0c0d0d0d0e0e000d05'